In [2]:
import pandas as pd
import numpy as np
import requests

In [4]:
from dotenv import load_dotenv
import os

load_dotenv(dotenv_path=r"C:\Users\Shiva\Projects\climate-risk-intelligence\.env")
api_key = os.getenv("OPENAQ_API_KEY")

In [5]:
    import requests

    headers = {"X-API-Key": api_key}

    response = requests.get("https://api.openaq.org/v3/locations?country_id=IN&limit=100", headers=headers)

    print(response.status_code)
    print(response.json())

401
{'detail': 'Invalid credentials'}

In [6]:
import requests

headers = {"X-API-Key": api_key}

response = requests.get("https://api.openaq.org/v3/locations?country_id=IN&limit=100&parameters_id=2",headers=headers)
print(response.status_code)
print(response.json())

401
{'detail': 'Invalid credentials'}

In [7]:
results = response.json()["results"]
df = pd.DataFrame(results)
india_df = df[df["country"].apply(lambda x: x["code"]) == "IN"]
print(f"Total locations: {len(df)}")
print(f"Indian locations: {len(india_df)}")
print(india_df["name"].values)

KeyError: 'results'

In [ ]:
collection_list = []
for x in range(1,11):
    response = requests.get(f"https://api.openaq.org/v3/locations?country_id=IN&limit=100&parameters_id=2&page={x}",headers=headers)
    collection = response.json()["results"]
    collection_list.extend(collection)
df = pd.DataFrame(collection_list)
india_df = df[df["country"].apply(lambda x: x["code"]) == "IN"]
print(f"Indian locations: {len(india_df)}")

Indian locations: 25

In [ ]:
print(india_df["name"].values)

<StringArray>
[                         'SPARTAN - IIT Kanpur',
  'Delhi Technological University, Delhi - CPCB',
                                   'IGI Airport',
                                   'Civil Lines',
                       'R K Puram, Delhi - DPCC',
                    'Punjabi Bagh, Delhi - DPCC',
               'Income Tax Office, Delhi - CPCB',
                 'Anand Vihar, New Delhi - DPCC',
                     'Mandir Marg, Delhi - DPCC',
                   'Collectorate - Gaya - BSPCB',
                 'Vikas Sadan, Gurugram - HSPCB',
                 'MD University, Rohtak - HSPCB',
                              'Lalbagh, DN Park',
                             'Alandur Bus Depot',
                   'Zoo Park, Hyderabad - TSPCB',
                     'Peenya, Bengaluru - KSPCB',
                           'IHBAS, Delhi - CPCB',
                 'BTM Layout, Bengaluru - KSPCB',
                        'Haldia, Haldia - WBPCB',
                  'Collectorate Jodhpur - RSPCB',
 'Rabindra Bharati University, Kolkata - WBSPCB',
                                    'Chandrapur',
                   'Sanjay Palace, Agra - UPPCB',
                    'Victoria Memorial - WBSPCB',
            'Collectorate - Muzaffarpur - BSPCB']
Length: 25, dtype: str

In [ ]:
india_df.to_csv("../data/india_aqi_locations.csv", index=False)

In [ ]:
clean_df = pd.DataFrame()
clean_df["id"] = india_df["id"]
clean_df["name"] = india_df["name"]
clean_df["latitude"] = india_df["coordinates"].apply(lambda x: x["latitude"])
clean_df["longitude"] = india_df["coordinates"].apply(lambda x: x["longitude"])
print(clean_df)

      id                                           name   latitude  longitude
9     12                           SPARTAN - IIT Kanpur  26.519000  80.233000
10    13   Delhi Technological University, Delhi - CPCB  28.744000  77.120000
12    15                                    IGI Airport  28.560000  77.094000
13    16                                    Civil Lines  28.678700  77.226200
14    17                        R K Puram, Delhi - DPCC  28.563262  77.186937
36    50                     Punjabi Bagh, Delhi - DPCC  28.674045  77.131023
64   103                Income Tax Office, Delhi - CPCB  28.623500  77.249400
116  235                  Anand Vihar, New Delhi - DPCC  28.646835  77.316032
117  236                      Mandir Marg, Delhi - DPCC  28.634100  77.200500
134  286                    Collectorate - Gaya - BSPCB  24.748969  84.943839
145  301                  Vikas Sadan, Gurugram - HSPCB  28.450124  77.026305
169  346                  MD University, Rohtak - HSPCB  28.876028  76.619464
172  354                               Lalbagh, DN Park  26.845786  80.938744
186  378                              Alandur Bus Depot  12.997114  80.191517
204  407                    Zoo Park, Hyderabad - TSPCB  17.349694  78.451437
206  412                      Peenya, Bengaluru - KSPCB  13.033900  77.513211
218  431                            IHBAS, Delhi - CPCB  28.682100  77.305000
309  594                  BTM Layout, Bengaluru - KSPCB  12.912811  77.609219
373  697                         Haldia, Haldia - WBPCB  22.060470  88.109737
376  703                   Collectorate Jodhpur - RSPCB  26.292064  73.037911
385  716  Rabindra Bharati University, Kolkata - WBSPCB  22.627875  88.380400
466  854                                     Chandrapur  19.950000  79.300000
471  860                    Sanjay Palace, Agra - UPPCB  27.198658  78.005981
503  910                     Victoria Memorial - WBSPCB  22.572646  88.363895
550  985             Collectorate - Muzaffarpur - BSPCB  26.076200  85.411500

In [ ]:
clean_df.to_csv("../data/india_aqi_locations.csv", index=False)

In [ ]:
import requests

headers = {"X-API-Key": api_key}
location_id = 12
response = requests.get(f"https://api.openaq.org/v3/locations/{location_id}/sensors",headers=headers)

print(response.status_code)
print(response.json())

200
{'meta': {'name': 'openaq-api', 'website': '/', 'page': 1, 'limit': 100, 'found': 1}, 'results': [{'id': 23, 'name': 'pm25 µg/m³', 'parameter': {'id': 2, 'name': 'pm25', 'units': 'µg/m³', 'displayName': 'PM2.5'}, 'datetimeFirst': None, 'datetimeLast': None, 'coverage': None, 'latest': None, 'summary': None}]}

In [ ]:
response = requests.get(f"https://api.openaq.org/v3/locations/17/sensors", headers=headers)
print(response.status_code)
print(response.json())

200
{'meta': {'name': 'openaq-api', 'website': '/', 'page': 1, 'limit': 100, 'found': 18}, 'results': [{'id': 399, 'name': 'pm10 µg/m³', 'parameter': {'id': 1, 'name': 'pm10', 'units': 'µg/m³', 'displayName': 'PM10'}, 'datetimeFirst': {'utc': '2016-02-05T14:55:00Z', 'local': '2016-02-05T20:25:00+05:30'}, 'datetimeLast': {'utc': '2018-02-21T21:15:00Z', 'local': '2018-02-22T02:45:00+05:30'}, 'coverage': {'expectedCount': 4, 'expectedInterval': '01:00:00', 'observedCount': 21117, 'observedInterval': '5279:15:00', 'percentComplete': 527925.0, 'percentCoverage': 527925.0, 'datetimeFrom': {'utc': '2016-02-05T14:55:00Z', 'local': '2016-02-05T20:25:00+05:30'}, 'datetimeTo': {'utc': '2018-02-21T21:15:00Z', 'local': '2018-02-22T02:45:00+05:30'}}, 'latest': {'datetime': {'utc': '2018-02-21T21:15:00Z', 'local': '2018-02-22T02:45:00+05:30'}, 'value': 339.0, 'coordinates': {'latitude': 28.563262, 'longitude': 77.186937}}, 'summary': {'min': 2.0, 'q02': None, 'q25': None, 'median': None, 'q75': None, 'q98': None, 'max': 1162.0, 'avg': 255.04404034664014, 'sd': None}}, {'id': 35, 'name': 'pm25 µg/m³', 'parameter': {'id': 2, 'name': 'pm25', 'units': 'µg/m³', 'displayName': 'PM2.5'}, 'datetimeFirst': {'utc': '2016-02-05T14:55:00Z', 'local': '2016-02-05T20:25:00+05:30'}, 'datetimeLast': {'utc': '2018-02-21T21:15:00Z', 'local': '2018-02-22T02:45:00+05:30'}, 'coverage': {'expectedCount': 4, 'expectedInterval': '01:00:00', 'observedCount': 19992, 'observedInterval': '4998:00:00', 'percentComplete': 499800.0, 'percentCoverage': 499800.0, 'datetimeFrom': {'utc': '2016-02-05T14:55:00Z', 'local': '2016-02-05T20:25:00+05:30'}, 'datetimeTo': {'utc': '2018-02-21T21:15:00Z', 'local': '2018-02-22T02:45:00+05:30'}}, 'latest': {'datetime': {'utc': '2018-02-21T21:15:00Z', 'local': '2018-02-22T02:45:00+05:30'}, 'value': 201.0, 'coordinates': {'latitude': 28.563262, 'longitude': 77.186937}}, 'summary': {'min': 6.0, 'q02': None, 'q25': None, 'median': None, 'q75': None, 'q98': None, 'max': 976.0, 'avg': 135.6907763105242, 'sd': None}}, {'id': 394, 'name': 'o3 µg/m³', 'parameter': {'id': 3, 'name': 'o3', 'units': 'µg/m³', 'displayName': 'O₃ mass'}, 'datetimeFirst': {'utc': '2016-02-05T14:55:00Z', 'local': '2016-02-05T20:25:00+05:30'}, 'datetimeLast': {'utc': '2018-01-24T09:30:00Z', 'local': '2018-01-24T15:00:00+05:30'}, 'coverage': {'expectedCount': 4, 'expectedInterval': '01:00:00', 'observedCount': 20787, 'observedInterval': '5196:45:00', 'percentComplete': 519675.0, 'percentCoverage': 519675.0, 'datetimeFrom': {'utc': '2016-02-05T14:55:00Z', 'local': '2016-02-05T20:25:00+05:30'}, 'datetimeTo': {'utc': '2018-01-24T09:30:00Z', 'local': '2018-01-24T15:00:00+05:30'}}, 'latest': {'datetime': {'utc': '2018-01-24T09:30:00Z', 'local': '2018-01-24T15:00:00+05:30'}, 'value': 95.33, 'coordinates': {'latitude': 28.563262, 'longitude': 77.186937}}, 'summary': {'min': 1.03, 'q02': None, 'q25': None, 'median': None, 'q75': None, 'q98': None, 'max': 492.7, 'avg': 48.48322653581561, 'sd': None}}, {'id': 36, 'name': 'no2 µg/m³', 'parameter': {'id': 5, 'name': 'no2', 'units': 'µg/m³', 'displayName': 'NO₂ mass'}, 'datetimeFirst': {'utc': '2016-02-05T14:55:00Z', 'local': '2016-02-05T20:25:00+05:30'}, 'datetimeLast': {'utc': '2018-02-21T20:45:00Z', 'local': '2018-02-22T02:15:00+05:30'}, 'coverage': {'expectedCount': 4, 'expectedInterval': '01:00:00', 'observedCount': 22237, 'observedInterval': '5559:15:00', 'percentComplete': 555925.0, 'percentCoverage': 555925.0, 'datetimeFrom': {'utc': '2016-02-05T14:55:00Z', 'local': '2016-02-05T20:25:00+05:30'}, 'datetimeTo': {'utc': '2018-02-21T20:45:00Z', 'local': '2018-02-22T02:15:00+05:30'}}, 'latest': {'datetime': {'utc': '2018-02-21T20:45:00Z', 'local': '2018-02-22T02:15:00+05:30'}, 'value': 77.6, 'coordinates': {'latitude': 28.563262, 'longitude': 77.186937}}, 'summary': {'min': 1.1, 'q02': None, 'q25': None, 'median': None, 'q75': None, 'q98': None, 'max': 801.8, 'avg': 71.20443450105682, 'sd': None}}, {'id': 392, 'name': 'co µg/m³', 'parameter': {'id': 4, 'name': 'co', 'units': 'µg/m³', 'displayName': 'CO mass'}, 'datetimeFirst': {'utc': '2016-02-05T14:55:00Z', 'local': '2016-02-05T20:25:00+05:30'}, 'datetimeLast': {'utc': '2018-02-21T20:45:00Z', 'local': '2018-02-22T02:15:00+05:30'}, 'coverage': {'expectedCount': 4, 'expectedInterval': '01:00:00', 'observedCount': 21647, 'observedInterval': '5411:45:00', 'percentComplete': 541175.0, 'percentCoverage': 541175.0, 'datetimeFrom': {'utc': '2016-02-05T14:55:00Z', 'local': '2016-02-05T20:25:00+05:30'}, 'datetimeTo': {'utc': '2018-02-21T20:45:00Z', 'local': '2018-02-22T02:15:00+05:30'}}, 'latest': {'datetime': {'utc': '2018-02-21T20:45:00Z', 'local': '2018-02-22T02:15:00+05:30'}, 'value': 4300.0, 'coordinates': {'latitude': 28.563262, 'longitude': 77.186937}}, 'summary': {'min': 0.0, 'q02': None, 'q25': None, 'median': None, 'q75': None, 'q98': None, 'max': 87030.0, 'avg': 2327.5248302305167, 'sd': None}}, {'id': 393, 'name': 'so2 µg/m³', 'parameter': {'id': 6, 'name': 'so2', 'units': 'µg/m³', 'displayName': 'SO₂ mass'}, 'datetimeFirst': {'utc': '2016-02-05T14:55:00Z', 'local': '2016-02-05T20:25:00+05:30'}, 'datetimeLast': {'utc': '2018-02-21T21:15:00Z', 'local': '2018-02-22T02:45:00+05:30'}, 'coverage': {'expectedCount': 4, 'expectedInterval': '01:00:00', 'observedCount': 7989, 'observedInterval': '1997:15:00', 'percentComplete': 199725.0, 'percentCoverage': 199725.0, 'datetimeFrom': {'utc': '2016-02-05T14:55:00Z', 'local': '2016-02-05T20:25:00+05:30'}, 'datetimeTo': {'utc': '2018-02-21T21:15:00Z', 'local': '2018-02-22T02:45:00+05:30'}}, 'latest': {'datetime': {'utc': '2018-02-21T21:15:00Z', 'local': '2018-02-22T02:45:00+05:30'}, 'value': 56.9, 'coordinates': {'latitude': 28.563262, 'longitude': 77.186937}}, 'summary': {'min': 0.0, 'q02': None, 'q25': None, 'median': None, 'q75': None, 'q98': None, 'max': 854.3, 'avg': 32.762061584678754, 'sd': None}}, {'id': 12234783, 'name': 'no ppb', 'parameter': {'id': 24, 'name': 'no', 'units': 'ppb', 'displayName': 'NO'}, 'datetimeFirst': {'utc': '2025-02-18T20:15:00Z', 'local': '2025-02-19T01:45:00+05:30'}, 'datetimeLast': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'coverage': {'expectedCount': 4, 'expectedInterval': '01:00:00', 'observedCount': 29289, 'observedInterval': '7322:15:00', 'percentComplete': 732225.0, 'percentCoverage': 732225.0, 'datetimeFrom': {'utc': '2025-02-18T20:15:00Z', 'local': '2025-02-19T01:45:00+05:30'}, 'datetimeTo': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}}, 'latest': {'datetime': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'value': 2.3, 'coordinates': {'latitude': 28.563262, 'longitude': 77.186937}}, 'summary': {'min': 0.0, 'q02': None, 'q25': None, 'median': None, 'q75': None, 'q98': None, 'max': 501.6, 'avg': 88.33333333333333, 'sd': 9.346523417827614}}, {'id': 12234785, 'name': 'o3 µg/m³', 'parameter': {'id': 3, 'name': 'o3', 'units': 'µg/m³', 'displayName': 'O₃ mass'}, 'datetimeFirst': {'utc': '2025-02-18T20:15:00Z', 'local': '2025-02-19T01:45:00+05:30'}, 'datetimeLast': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'coverage': {'expectedCount': 4, 'expectedInterval': '01:00:00', 'observedCount': 28877, 'observedInterval': '7219:15:00', 'percentComplete': 721925.0, 'percentCoverage': 721925.0, 'datetimeFrom': {'utc': '2025-02-18T20:15:00Z', 'local': '2025-02-19T01:45:00+05:30'}, 'datetimeTo': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}}, 'latest': {'datetime': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'value': 16.3, 'coordinates': {'latitude': 28.563262, 'longitude': 77.186937}}, 'summary': {'min': 0.0, 'q02': None, 'q25': None, 'median': None, 'q75': None, 'q98': None, 'max': 485.5, 'avg': 15.899999999999999, 'sd': 0.7576278769950328}}, {'id': 12234787, 'name': 'pm25 µg/m³', 'parameter': {'id': 2, 'name': 'pm25', 'units': 'µg/m³', 'displayName': 'PM2.5'}, 'datetimeFirst': {'utc': '2025-02-18T20:15:00Z', 'local': '2025-02-19T01:45:00+05:30'}, 'datetimeLast': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'coverage': {'expectedCount': 4, 'expectedInterval': '01:00:00', 'observedCount': 30064, 'observedInterval': '7516:00:00', 'percentComplete': 751600.0, 'percentCoverage': 751600.0, 'datetimeFrom': {'utc': '2025-02-18T20:15:00Z', 'local': '2025-02-19T01:45:00+05:30'}, 'datetimeTo': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}}, 'latest': {'datetime': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'value': 63.0, 'coordinates': {'latitude': 28.563262, 'longitude': 77.186937}}, 'summary': {'min': 1.0, 'q02': None, 'q25': None, 'median': None, 'q75': None, 'q98': None, 'max': 1656.0, 'avg': 99.18181818181819, 'sd': 12.351665327543342}}, {'id': 12234784, 'name': 'no2 ppb', 'parameter': {'id': 15, 'name': 'no2', 'units': 'ppb', 'displayName': 'NO₂'}, 'datetimeFirst': {'utc': '2025-02-18T20:15:00Z', 'local': '2025-02-19T01:45:00+05:30'}, 'datetimeLast': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'coverage': {'expectedCount': 4, 'expectedInterval': '01:00:00', 'observedCount': 29449, 'observedInterval': '7362:15:00', 'percentComplete': 736225.0, 'percentCoverage': 736225.0, 'datetimeFrom': {'utc': '2025-02-18T20:15:00Z', 'local': '2025-02-19T01:45:00+05:30'}, 'datetimeTo': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}}, 'latest': {'datetime': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'value': 62.3, 'coordinates': {'latitude': 28.563262, 'longitude': 77.186937}}, 'summary': {'min': 0.1, 'q02': None, 'q25': None, 'median': None, 'q75': None, 'q98': None, 'max': 219.7, 'avg': 45.94444444444445, 'sd': 5.855363163611442}}, {'id': 12234786, 'name': 'pm10 µg/m³', 'parameter': {'id': 1, 'name': 'pm10', 'units': 'µg/m³', 'displayName': 'PM10'}, 'datetimeFirst': {'utc': '2025-02-18T20:30:00Z', 'local': '2025-02-19T02:00:00+05:30'}, 'datetimeLast': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'coverage': {'expectedCount': 4, 'expectedInterval': '01:00:00', 'observedCount': 28905, 'observedInterval': '7226:15:00', 'percentComplete': 722625.0, 'percentCoverage': 722625.0, 'datetimeFrom': {'utc': '2025-02-18T20:30:00Z', 'local': '2025-02-19T02:00:00+05:30'}, 'datetimeTo': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}}, 'latest': {'datetime': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'value': 149.0, 'coordinates': {'latitude': 28.563262, 'longitude': 77.186937}}, 'summary': {'min': 1.0, 'q02': None, 'q25': None, 'median': None, 'q75': None, 'q98': None, 'max': 2671.0, 'avg': 179.625, 'sd': 11.758735354741901}}, {'id': 12234782, 'name': 'co ppb', 'parameter': {'id': 102, 'name': 'co', 'units': 'ppb', 'displayName': 'CO'}, 'datetimeFirst': {'utc': '2025-02-18T20:15:00Z', 'local': '2025-02-19T01:45:00+05:30'}, 'datetimeLast': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'coverage': {'expectedCount': 4, 'expectedInterval': '01:00:00', 'observedCount': 28846, 'observedInterval': '7211:30:00', 'percentComplete': 721150.0, 'percentCoverage': 721150.0, 'datetimeFrom': {'utc': '2025-02-18T20:15:00Z', 'local': '2025-02-19T01:45:00+05:30'}, 'datetimeTo': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}}, 'latest': {'datetime': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'value': 0.74, 'coordinates': {'latitude': 28.563262, 'longitude': 77.186937}}, 'summary': {'min': 0.0, 'q02': None, 'q25': None, 'median': None, 'q75': None, 'q98': None, 'max': 9.54, 'avg': 1.27, 'sd': 0.24994999499899975}}, {'id': 12234790, 'name': 'temperature c', 'parameter': {'id': 100, 'name': 'temperature', 'units': 'c', 'displayName': 'Temperature (C)'}, 'datetimeFirst': {'utc': '2025-02-18T20:15:00Z', 'local': '2025-02-19T01:45:00+05:30'}, 'datetimeLast': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'coverage': {'expectedCount': 4, 'expectedInterval': '01:00:00', 'observedCount': 30557, 'observedInterval': '7639:15:00', 'percentComplete': 763925.0, 'percentCoverage': 763925.0, 'datetimeFrom': {'utc': '2025-02-18T20:15:00Z', 'local': '2025-02-19T01:45:00+05:30'}, 'datetimeTo': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}}, 'latest': {'datetime': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'value': 15.4, 'coordinates': {'latitude': 28.563262, 'longitude': 77.186937}}, 'summary': {'min': 6.7, 'q02': None, 'q25': None, 'median': None, 'q75': None, 'q98': None, 'max': 44.3, 'avg': 16.063636363636363, 'sd': 0.17477257950106034}}, {'id': 12234788, 'name': 'relativehumidity %', 'parameter': {'id': 98, 'name': 'relativehumidity', 'units': '%', 'displayName': 'RH'}, 'datetimeFirst': {'utc': '2025-02-18T20:15:00Z', 'local': '2025-02-19T01:45:00+05:30'}, 'datetimeLast': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'coverage': {'expectedCount': 4, 'expectedInterval': '01:00:00', 'observedCount': 30557, 'observedInterval': '7639:15:00', 'percentComplete': 763925.0, 'percentCoverage': 763925.0, 'datetimeFrom': {'utc': '2025-02-18T20:15:00Z', 'local': '2025-02-19T01:45:00+05:30'}, 'datetimeTo': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}}, 'latest': {'datetime': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'value': 71.0, 'coordinates': {'latitude': 28.563262, 'longitude': 77.186937}}, 'summary': {'min': 18.0, 'q02': None, 'q25': None, 'median': None, 'q75': None, 'q98': None, 'max': 96.0, 'avg': 84.54545454545455, 'sd': 0.6875516509523286}}, {'id': 12234789, 'name': 'so2 ppb', 'parameter': {'id': 101, 'name': 'so2', 'units': 'ppb', 'displayName': 'SO₂'}, 'datetimeFirst': {'utc': '2025-02-18T20:15:00Z', 'local': '2025-02-19T01:45:00+05:30'}, 'datetimeLast': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'coverage': {'expectedCount': 4, 'expectedInterval': '01:00:00', 'observedCount': 28110, 'observedInterval': '7027:30:00', 'percentComplete': 702750.0, 'percentCoverage': 702750.0, 'datetimeFrom': {'utc': '2025-02-18T20:15:00Z', 'local': '2025-02-19T01:45:00+05:30'}, 'datetimeTo': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}}, 'latest': {'datetime': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'value': 3.5, 'coordinates': {'latitude': 28.563262, 'longitude': 77.186937}}, 'summary': {'min': 0.0, 'q02': None, 'q25': None, 'median': None, 'q75': None, 'q98': None, 'max': 2021.5, 'avg': 33.22222222222222, 'sd': 2.6142770404921585}}, {'id': 14340715, 'name': 'wind_speed m/s', 'parameter': {'id': 34, 'name': 'wind_speed', 'units': 'm/s', 'displayName': 'Wind speed'}, 'datetimeFirst': {'utc': '2025-10-10T18:15:00Z', 'local': '2025-10-10T23:45:00+05:30'}, 'datetimeLast': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'coverage': {'expectedCount': 4, 'expectedInterval': '01:00:00', 'observedCount': 11438, 'observedInterval': '2859:30:00', 'percentComplete': 285950.0, 'percentCoverage': 285950.0, 'datetimeFrom': {'utc': '2025-10-10T18:15:00Z', 'local': '2025-10-10T23:45:00+05:30'}, 'datetimeTo': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}}, 'latest': {'datetime': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'value': 0.6, 'coordinates': {'latitude': 28.563262, 'longitude': 77.186937}}, 'summary': {'min': 0.3, 'q02': None, 'q25': None, 'median': None, 'q75': None, 'q98': None, 'max': 2.9, 'avg': 0.3, 'sd': 0.0}}, {'id': 14340714, 'name': 'wind_direction deg', 'parameter': {'id': 22, 'name': 'wind_direction', 'units': 'deg', 'displayName': 'Wind direction'}, 'datetimeFirst': {'utc': '2025-10-10T18:15:00Z', 'local': '2025-10-10T23:45:00+05:30'}, 'datetimeLast': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'coverage': {'expectedCount': 4, 'expectedInterval': '01:00:00', 'observedCount': 11436, 'observedInterval': '2859:00:00', 'percentComplete': 285900.0, 'percentCoverage': 285900.0, 'datetimeFrom': {'utc': '2025-10-10T18:15:00Z', 'local': '2025-10-10T23:45:00+05:30'}, 'datetimeTo': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}}, 'latest': {'datetime': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'value': 210.0, 'coordinates': {'latitude': 28.563262, 'longitude': 77.186937}}, 'summary': {'min': 7.0, 'q02': None, 'q25': None, 'median': None, 'q75': None, 'q98': None, 'max': 340.0, 'avg': 212.0, 'sd': 0.0}}, {'id': 14340713, 'name': 'nox ppb', 'parameter': {'id': 23, 'name': 'nox', 'units': 'ppb', 'displayName': 'NOX'}, 'datetimeFirst': {'utc': '2025-10-10T18:15:00Z', 'local': '2025-10-10T23:45:00+05:30'}, 'datetimeLast': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'coverage': {'expectedCount': 4, 'expectedInterval': '01:00:00', 'observedCount': 11187, 'observedInterval': '2796:45:00', 'percentComplete': 279675.0, 'percentCoverage': 279675.0, 'datetimeFrom': {'utc': '2025-10-10T18:15:00Z', 'local': '2025-10-10T23:45:00+05:30'}, 'datetimeTo': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}}, 'latest': {'datetime': {'utc': '2026-03-17T00:30:00Z', 'local': '2026-03-17T06:00:00+05:30'}, 'value': 0.035, 'coordinates': {'latitude': 28.563262, 'longitude': 77.186937}}, 'summary': {'min': 0.001, 'q02': None, 'q25': None, 'median': None, 'q75': None, 'q98': None, 'max': 0.32, 'avg': 0.10690000000000001, 'sd': 0.0}}]}

In [ ]:
import time

collection_list = []

for location_id, name in zip(clean_df["id"], clean_df["name"]):
    try:
        response = requests.get(
            f"https://api.openaq.org/v3/locations/{location_id}/sensors",
            headers=headers,
            timeout=30
        )
        if response.status_code == 200:
            for sensor in response.json()["results"]:
                if sensor["parameter"]["name"] == "pm25":
                    if sensor["summary"] is not None:
                        avg = sensor["summary"]["avg"]
                        collection_list.append((location_id, name, avg))
    except Exception as e:
        print(f"Failed for {name}: {e}")
    time.sleep(0.5)

df = pd.DataFrame(collection_list, columns=["location_id", "name", "pm25_avg"])
print(df)

    location_id                                           name     pm25_avg
0            13   Delhi Technological University, Delhi - CPCB   172.831336
1            17                        R K Puram, Delhi - DPCC   135.690776
2            17                        R K Puram, Delhi - DPCC    99.181818
3            50                     Punjabi Bagh, Delhi - DPCC   128.774238
4            50                     Punjabi Bagh, Delhi - DPCC   118.272727
5           103                Income Tax Office, Delhi - CPCB   141.592259
6           235                  Anand Vihar, New Delhi - DPCC   157.999618
7           235                  Anand Vihar, New Delhi - DPCC   100.000000
8           236                      Mandir Marg, Delhi - DPCC   113.032575
9           286                    Collectorate - Gaya - BSPCB    82.862666
10          301                  Vikas Sadan, Gurugram - HSPCB   114.570686
11          301                  Vikas Sadan, Gurugram - HSPCB  2112.883333
12          346                  MD University, Rohtak - HSPCB    89.971503
13          354                               Lalbagh, DN Park   135.052329
14          378                              Alandur Bus Depot    53.568709
15          407                    Zoo Park, Hyderabad - TSPCB    48.485878
16          407                    Zoo Park, Hyderabad - TSPCB    61.000000
17          412                      Peenya, Bengaluru - KSPCB    44.591306
18          431                            IHBAS, Delhi - CPCB    99.456788
19          594                  BTM Layout, Bengaluru - KSPCB    28.171332
20          697                         Haldia, Haldia - WBPCB    41.508556
21          703                   Collectorate Jodhpur - RSPCB    90.795043
22          716  Rabindra Bharati University, Kolkata - WBSPCB    34.600000
23          854                                     Chandrapur    64.744416
24          860                    Sanjay Palace, Agra - UPPCB    92.157854
25          860                    Sanjay Palace, Agra - UPPCB    12.600000
26          910                     Victoria Memorial - WBSPCB     0.000000
27          985             Collectorate - Muzaffarpur - BSPCB   114.291053

In [ ]:
print(clean_df["name"].head())

9                             SPARTAN - IIT Kanpur
10    Delhi Technological University, Delhi - CPCB
12                                     IGI Airport
13                                     Civil Lines
14                         R K Puram, Delhi - DPCC
Name: name, dtype: str

In [ ]:
pd.read_csv(r"C:\Users\Shiva\Projects\climate-risk-intelligence\data\india_aqi_locations.csv")

     id                                           name   latitude  longitude
0    12                           SPARTAN - IIT Kanpur  26.519000  80.233000
1    13   Delhi Technological University, Delhi - CPCB  28.744000  77.120000
2    15                                    IGI Airport  28.560000  77.094000
3    16                                    Civil Lines  28.678700  77.226200
4    17                        R K Puram, Delhi - DPCC  28.563262  77.186937
5    50                     Punjabi Bagh, Delhi - DPCC  28.674045  77.131023
6   103                Income Tax Office, Delhi - CPCB  28.623500  77.249400
7   235                  Anand Vihar, New Delhi - DPCC  28.646835  77.316032
8   236                      Mandir Marg, Delhi - DPCC  28.634100  77.200500
9   286                    Collectorate - Gaya - BSPCB  24.748969  84.943839
10  301                  Vikas Sadan, Gurugram - HSPCB  28.450124  77.026305
11  346                  MD University, Rohtak - HSPCB  28.876028  76.619464
12  354                               Lalbagh, DN Park  26.845786  80.938744
13  378                              Alandur Bus Depot  12.997114  80.191517
14  407                    Zoo Park, Hyderabad - TSPCB  17.349694  78.451437
15  412                      Peenya, Bengaluru - KSPCB  13.033900  77.513211
16  431                            IHBAS, Delhi - CPCB  28.682100  77.305000
17  594                  BTM Layout, Bengaluru - KSPCB  12.912811  77.609219
18  697                         Haldia, Haldia - WBPCB  22.060470  88.109737
19  703                   Collectorate Jodhpur - RSPCB  26.292064  73.037911
20  716  Rabindra Bharati University, Kolkata - WBSPCB  22.627875  88.380400
21  854                                     Chandrapur  19.950000  79.300000
22  860                    Sanjay Palace, Agra - UPPCB  27.198658  78.005981
23  910                     Victoria Memorial - WBSPCB  22.572646  88.363895
24  985             Collectorate - Muzaffarpur - BSPCB  26.076200  85.411500

In [ ]:
print(clean_df.head())
print(clean_df.columns.tolist())

    id                                          name   latitude  longitude
9   12                          SPARTAN - IIT Kanpur  26.519000  80.233000
10  13  Delhi Technological University, Delhi - CPCB  28.744000  77.120000
12  15                                   IGI Airport  28.560000  77.094000
13  16                                   Civil Lines  28.678700  77.226200
14  17                       R K Puram, Delhi - DPCC  28.563262  77.186937
['id', 'name', 'latitude', 'longitude']

In [ ]:
clean_df = pd.DataFrame()
clean_df["id"] = india_df["id"]
clean_df["name"] = india_df["name"]
clean_df["latitude"] = india_df["coordinates"].apply(lambda x: x["latitude"])
clean_df["longitude"] = india_df["coordinates"].apply(lambda x: x["longitude"])
print(clean_df)

      id                                           name   latitude  longitude
9     12                           SPARTAN - IIT Kanpur  26.519000  80.233000
10    13   Delhi Technological University, Delhi - CPCB  28.744000  77.120000
12    15                                    IGI Airport  28.560000  77.094000
13    16                                    Civil Lines  28.678700  77.226200
14    17                        R K Puram, Delhi - DPCC  28.563262  77.186937
36    50                     Punjabi Bagh, Delhi - DPCC  28.674045  77.131023
64   103                Income Tax Office, Delhi - CPCB  28.623500  77.249400
116  235                  Anand Vihar, New Delhi - DPCC  28.646835  77.316032
117  236                      Mandir Marg, Delhi - DPCC  28.634100  77.200500
134  286                    Collectorate - Gaya - BSPCB  24.748969  84.943839
145  301                  Vikas Sadan, Gurugram - HSPCB  28.450124  77.026305
169  346                  MD University, Rohtak - HSPCB  28.876028  76.619464
172  354                               Lalbagh, DN Park  26.845786  80.938744
186  378                              Alandur Bus Depot  12.997114  80.191517
204  407                    Zoo Park, Hyderabad - TSPCB  17.349694  78.451437
206  412                      Peenya, Bengaluru - KSPCB  13.033900  77.513211
218  431                            IHBAS, Delhi - CPCB  28.682100  77.305000
309  594                  BTM Layout, Bengaluru - KSPCB  12.912811  77.609219
373  697                         Haldia, Haldia - WBPCB  22.060470  88.109737
376  703                   Collectorate Jodhpur - RSPCB  26.292064  73.037911
385  716  Rabindra Bharati University, Kolkata - WBSPCB  22.627875  88.380400
466  854                                     Chandrapur  19.950000  79.300000
471  860                    Sanjay Palace, Agra - UPPCB  27.198658  78.005981
503  910                     Victoria Memorial - WBSPCB  22.572646  88.363895
550  985             Collectorate - Muzaffarpur - BSPCB  26.076200  85.411500

In [ ]:
import time

collection_list = []

for location_id, name in zip(clean_df["id"], clean_df["name"]):
    try:
        response = requests.get(
            f"https://api.openaq.org/v3/locations/{location_id}/sensors",
            headers=headers,
            timeout=30
        )
        if response.status_code == 200:
            for sensor in response.json()["results"]:
                if sensor["parameter"]["name"] == "pm25":
                    if sensor["summary"] is not None:
                        avg = sensor["summary"]["avg"]
                        collection_list.append((location_id, name, avg))
    except Exception as e:
        print(f"Failed for {name}: {e}")
    time.sleep(0.5)

df = pd.DataFrame(collection_list, columns=["location_id", "name", "pm25_avg"])
print(df)

    location_id                                           name     pm25_avg
0            13   Delhi Technological University, Delhi - CPCB   172.831336
1            17                        R K Puram, Delhi - DPCC   135.690776
2            17                        R K Puram, Delhi - DPCC    99.181818
3            50                     Punjabi Bagh, Delhi - DPCC   128.774238
4            50                     Punjabi Bagh, Delhi - DPCC   118.272727
5           103                Income Tax Office, Delhi - CPCB   141.592259
6           235                  Anand Vihar, New Delhi - DPCC   157.999618
7           235                  Anand Vihar, New Delhi - DPCC   100.000000
8           236                      Mandir Marg, Delhi - DPCC   113.032575
9           286                    Collectorate - Gaya - BSPCB    82.862666
10          301                  Vikas Sadan, Gurugram - HSPCB   114.570686
11          301                  Vikas Sadan, Gurugram - HSPCB  2112.883333
12          346                  MD University, Rohtak - HSPCB    89.971503
13          354                               Lalbagh, DN Park   135.052329
14          378                              Alandur Bus Depot    53.568709
15          407                    Zoo Park, Hyderabad - TSPCB    48.485878
16          407                    Zoo Park, Hyderabad - TSPCB    61.000000
17          412                      Peenya, Bengaluru - KSPCB    44.591306
18          431                            IHBAS, Delhi - CPCB    99.456788
19          594                  BTM Layout, Bengaluru - KSPCB    28.171332
20          697                         Haldia, Haldia - WBPCB    41.508556
21          703                   Collectorate Jodhpur - RSPCB    90.795043
22          716  Rabindra Bharati University, Kolkata - WBSPCB    34.600000
23          854                                     Chandrapur    64.744416
24          860                    Sanjay Palace, Agra - UPPCB    92.157854
25          860                    Sanjay Palace, Agra - UPPCB    12.600000
26          910                     Victoria Memorial - WBSPCB     0.000000
27          985             Collectorate - Muzaffarpur - BSPCB   114.291053

In [ ]:
pm25_avg_over_900 = df[(df["pm25_avg"] < 900) & (df["pm25_avg"] > 0)]
clean_df["location_id"] = clean_df["id"]
pm25_avg_filtered = np.round(pm25_avg_over_900.groupby(["location_id"])["pm25_avg"].mean().reset_index(),2)
merged_df = pd.merge(clean_df,pm25_avg_filtered,on="location_id",how="left")
print(merged_df)

     id                                           name   latitude  longitude  \
0    12                           SPARTAN - IIT Kanpur  26.519000  80.233000
1    13   Delhi Technological University, Delhi - CPCB  28.744000  77.120000
2    15                                    IGI Airport  28.560000  77.094000
3    16                                    Civil Lines  28.678700  77.226200
4    17                        R K Puram, Delhi - DPCC  28.563262  77.186937
5    50                     Punjabi Bagh, Delhi - DPCC  28.674045  77.131023
6   103                Income Tax Office, Delhi - CPCB  28.623500  77.249400
7   235                  Anand Vihar, New Delhi - DPCC  28.646835  77.316032
8   236                      Mandir Marg, Delhi - DPCC  28.634100  77.200500
9   286                    Collectorate - Gaya - BSPCB  24.748969  84.943839
10  301                  Vikas Sadan, Gurugram - HSPCB  28.450124  77.026305
11  346                  MD University, Rohtak - HSPCB  28.876028  76.619464
12  354                               Lalbagh, DN Park  26.845786  80.938744
13  378                              Alandur Bus Depot  12.997114  80.191517
14  407                    Zoo Park, Hyderabad - TSPCB  17.349694  78.451437
15  412                      Peenya, Bengaluru - KSPCB  13.033900  77.513211
16  431                            IHBAS, Delhi - CPCB  28.682100  77.305000
17  594                  BTM Layout, Bengaluru - KSPCB  12.912811  77.609219
18  697                         Haldia, Haldia - WBPCB  22.060470  88.109737
19  703                   Collectorate Jodhpur - RSPCB  26.292064  73.037911
20  716  Rabindra Bharati University, Kolkata - WBSPCB  22.627875  88.380400
21  854                                     Chandrapur  19.950000  79.300000
22  860                    Sanjay Palace, Agra - UPPCB  27.198658  78.005981
23  910                     Victoria Memorial - WBSPCB  22.572646  88.363895
24  985             Collectorate - Muzaffarpur - BSPCB  26.076200  85.411500

    location_id  pm25_avg
0            12       NaN
1            13    172.83
2            15       NaN
3            16       NaN
4            17    117.44
5            50    123.52
6           103    141.59
7           235    129.00
8           236    113.03
9           286     82.86
10          301    114.57
11          346     89.97
12          354    135.05
13          378     53.57
14          407     54.74
15          412     44.59
16          431     99.46
17          594     28.17
18          697     41.51
19          703     90.80
20          716     34.60
21          854     64.74
22          860     52.38
23          910       NaN
24          985    114.29

In [ ]:
merged_df = merged_df.drop(columns="location_id")
merged_df = merged_df.dropna()
print(merged_df)

     id                                           name   latitude  longitude  \
1    13   Delhi Technological University, Delhi - CPCB  28.744000  77.120000
4    17                        R K Puram, Delhi - DPCC  28.563262  77.186937
5    50                     Punjabi Bagh, Delhi - DPCC  28.674045  77.131023
6   103                Income Tax Office, Delhi - CPCB  28.623500  77.249400
7   235                  Anand Vihar, New Delhi - DPCC  28.646835  77.316032
8   236                      Mandir Marg, Delhi - DPCC  28.634100  77.200500
9   286                    Collectorate - Gaya - BSPCB  24.748969  84.943839
10  301                  Vikas Sadan, Gurugram - HSPCB  28.450124  77.026305
11  346                  MD University, Rohtak - HSPCB  28.876028  76.619464
12  354                               Lalbagh, DN Park  26.845786  80.938744
13  378                              Alandur Bus Depot  12.997114  80.191517
14  407                    Zoo Park, Hyderabad - TSPCB  17.349694  78.451437
15  412                      Peenya, Bengaluru - KSPCB  13.033900  77.513211
16  431                            IHBAS, Delhi - CPCB  28.682100  77.305000
17  594                  BTM Layout, Bengaluru - KSPCB  12.912811  77.609219
18  697                         Haldia, Haldia - WBPCB  22.060470  88.109737
19  703                   Collectorate Jodhpur - RSPCB  26.292064  73.037911
20  716  Rabindra Bharati University, Kolkata - WBSPCB  22.627875  88.380400
21  854                                     Chandrapur  19.950000  79.300000
22  860                    Sanjay Palace, Agra - UPPCB  27.198658  78.005981
24  985             Collectorate - Muzaffarpur - BSPCB  26.076200  85.411500

    pm25_avg
1     172.83
4     117.44
5     123.52
6     141.59
7     129.00
8     113.03
9      82.86
10    114.57
11     89.97
12    135.05
13     53.57
14     54.74
15     44.59
16     99.46
17     28.17
18     41.51
19     90.80
20     34.60
21     64.74
22     52.38
24    114.29

In [ ]:
merged_df.to_csv(r"C:\Users\Shiva\Projects\climate-risk-intelligence\data\india_aqi_final.csv", index=False)

In [ ]:

features_df = pd.read_csv(r"C:\Users\Shiva\Projects\climate-risk-intelligence\data\india_aqi_final.csv")
print(features_df)

     id                                           name   latitude  longitude  \
0    13   Delhi Technological University, Delhi - CPCB  28.744000  77.120000
1    17                        R K Puram, Delhi - DPCC  28.563262  77.186937
2    50                     Punjabi Bagh, Delhi - DPCC  28.674045  77.131023
3   103                Income Tax Office, Delhi - CPCB  28.623500  77.249400
4   235                  Anand Vihar, New Delhi - DPCC  28.646835  77.316032
5   236                      Mandir Marg, Delhi - DPCC  28.634100  77.200500
6   286                    Collectorate - Gaya - BSPCB  24.748969  84.943839
7   301                  Vikas Sadan, Gurugram - HSPCB  28.450124  77.026305
8   346                  MD University, Rohtak - HSPCB  28.876028  76.619464
9   354                               Lalbagh, DN Park  26.845786  80.938744
10  378                              Alandur Bus Depot  12.997114  80.191517
11  407                    Zoo Park, Hyderabad - TSPCB  17.349694  78.451437
12  412                      Peenya, Bengaluru - KSPCB  13.033900  77.513211
13  431                            IHBAS, Delhi - CPCB  28.682100  77.305000
14  594                  BTM Layout, Bengaluru - KSPCB  12.912811  77.609219
15  697                         Haldia, Haldia - WBPCB  22.060470  88.109737
16  703                   Collectorate Jodhpur - RSPCB  26.292064  73.037911
17  716  Rabindra Bharati University, Kolkata - WBSPCB  22.627875  88.380400
18  854                                     Chandrapur  19.950000  79.300000
19  860                    Sanjay Palace, Agra - UPPCB  27.198658  78.005981
20  985             Collectorate - Muzaffarpur - BSPCB  26.076200  85.411500

    pm25_avg
0     172.83
1     117.44
2     123.52
3     141.59
4     129.00
5     113.03
6      82.86
7     114.57
8      89.97
9     135.05
10     53.57
11     54.74
12     44.59
13     99.46
14     28.17
15     41.51
16     90.80
17     34.60
18     64.74
19     52.38
20    114.29

In [ ]:
custom_bins = [0,30,60,90,120,250,float('inf')]
group_names = ['Good','Moderate','Unhealthy for sensitive groups','Unhealthy','Very Unhealthy','Hazardous']

features_df["risk_category"] = pd.cut(features_df["pm25_avg"],bins=custom_bins,labels = group_names,right=False)
features_df[["name", "pm25_avg", "risk_category"]]

,name,pm25_avg,risk_category
0,"Delhi Technological University, Delhi - CPCB",172.83,Very Unhealthy
1,"R K Puram, Delhi - DPCC",117.44,Unhealthy
2,"Punjabi Bagh, Delhi - DPCC",123.52,Very Unhealthy
3,"Income Tax Office, Delhi - CPCB",141.59,Very Unhealthy
4,"Anand Vihar, New Delhi - DPCC",129.00,Very Unhealthy
5,"Mandir Marg, Delhi - DPCC",113.03,Unhealthy
6,Collectorate - Gaya - BSPCB,82.86,Unhealthy for sensitive groups
7,"Vikas Sadan, Gurugram - HSPCB",114.57,Unhealthy
8,"MD University, Rohtak - HSPCB",89.97,Unhealthy for sensitive groups
9,"Lalbagh, DN Park",135.05,Very Unhealthy
10,Alandur Bus Depot,53.57,Moderate
11,"Zoo Park, Hyderabad - TSPCB",54.74,Moderate
12,"Peenya, Bengaluru - KSPCB",44.59,Moderate
13,"IHBAS, Delhi - CPCB",99.46,Unhealthy
14,"BTM Layout, Bengaluru - KSPCB",28.17,Good
15,"Haldia, Haldia - WBPCB",41.51,Moderate
16,Collectorate Jodhpur - RSPCB,90.80,Unhealthy
17,"Rabindra Bharati University, Kolkata - WBSPCB",34.60,Moderate
18,Chandrapur,64.74,Unhealthy for sensitive groups
19,"Sanjay Palace, Agra - UPPCB",52.38,Moderate
20,Collectorate - Muzaffarpur - BSPCB,114.29,Unhealthy

In [ ]:
features_df["pm25_normalized"] = np.round((features_df["pm25_avg"] - features_df["pm25_avg"].min()) / (features_df["pm25_avg"].max() - features_df["pm25_avg"].min()),2)
print(features_df.head())

    id                                          name   latitude  longitude  \
0   13  Delhi Technological University, Delhi - CPCB  28.744000  77.120000
1   17                       R K Puram, Delhi - DPCC  28.563262  77.186937
2   50                    Punjabi Bagh, Delhi - DPCC  28.674045  77.131023
3  103               Income Tax Office, Delhi - CPCB  28.623500  77.249400
4  235                 Anand Vihar, New Delhi - DPCC  28.646835  77.316032

   pm25_avg   risk_category  pm25_normalized
0    172.83  Very Unhealthy             1.00
1    117.44       Unhealthy             0.62
2    123.52  Very Unhealthy             0.66
3    141.59  Very Unhealthy             0.78
4    129.00  Very Unhealthy             0.70

In [ ]:
features_df["region"] = features_df.apply(lambda row: "East" if row['longitude'] > 80 else "West" if row['longitude'] < 76 else "North" if row['latitude'] > 26 and row['longitude'] > 76 and row['longitude'] < 80 else "South" if row['latitude'] < 22 and row['longitude'] > 76 and row['longitude'] < 80 else "Central",axis = 1)
print(features_df[["name","region","pm25_avg"]])

                                             name region  pm25_avg
0    Delhi Technological University, Delhi - CPCB  North    172.83
1                         R K Puram, Delhi - DPCC  North    117.44
2                      Punjabi Bagh, Delhi - DPCC  North    123.52
3                 Income Tax Office, Delhi - CPCB  North    141.59
4                   Anand Vihar, New Delhi - DPCC  North    129.00
5                       Mandir Marg, Delhi - DPCC  North    113.03
6                     Collectorate - Gaya - BSPCB   East     82.86
7                   Vikas Sadan, Gurugram - HSPCB  North    114.57
8                   MD University, Rohtak - HSPCB  North     89.97
9                                Lalbagh, DN Park   East    135.05
10                              Alandur Bus Depot   East     53.57
11                    Zoo Park, Hyderabad - TSPCB  South     54.74
12                      Peenya, Bengaluru - KSPCB  South     44.59
13                            IHBAS, Delhi - CPCB  North     99.46
14                  BTM Layout, Bengaluru - KSPCB  South     28.17
15                         Haldia, Haldia - WBPCB   East     41.51
16                   Collectorate Jodhpur - RSPCB   West     90.80
17  Rabindra Bharati University, Kolkata - WBSPCB   East     34.60
18                                     Chandrapur  South     64.74
19                    Sanjay Palace, Agra - UPPCB  North     52.38
20             Collectorate - Muzaffarpur - BSPCB   East    114.29

In [ ]:

print(features_df)

     id                                           name   latitude  longitude  \
0    13   Delhi Technological University, Delhi - CPCB  28.744000  77.120000
1    17                        R K Puram, Delhi - DPCC  28.563262  77.186937
2    50                     Punjabi Bagh, Delhi - DPCC  28.674045  77.131023
3   103                Income Tax Office, Delhi - CPCB  28.623500  77.249400
4   235                  Anand Vihar, New Delhi - DPCC  28.646835  77.316032
5   236                      Mandir Marg, Delhi - DPCC  28.634100  77.200500
6   286                    Collectorate - Gaya - BSPCB  24.748969  84.943839
7   301                  Vikas Sadan, Gurugram - HSPCB  28.450124  77.026305
8   346                  MD University, Rohtak - HSPCB  28.876028  76.619464
9   354                               Lalbagh, DN Park  26.845786  80.938744
10  378                              Alandur Bus Depot  12.997114  80.191517
11  407                    Zoo Park, Hyderabad - TSPCB  17.349694  78.451437
12  412                      Peenya, Bengaluru - KSPCB  13.033900  77.513211
13  431                            IHBAS, Delhi - CPCB  28.682100  77.305000
14  594                  BTM Layout, Bengaluru - KSPCB  12.912811  77.609219
15  697                         Haldia, Haldia - WBPCB  22.060470  88.109737
16  703                   Collectorate Jodhpur - RSPCB  26.292064  73.037911
17  716  Rabindra Bharati University, Kolkata - WBSPCB  22.627875  88.380400
18  854                                     Chandrapur  19.950000  79.300000
19  860                    Sanjay Palace, Agra - UPPCB  27.198658  78.005981
20  985             Collectorate - Muzaffarpur - BSPCB  26.076200  85.411500

    pm25_avg                   risk_category  pm25_normalized region
0     172.83                  Very Unhealthy             1.00  North
1     117.44                       Unhealthy             0.62  North
2     123.52                  Very Unhealthy             0.66  North
3     141.59                  Very Unhealthy             0.78  North
4     129.00                  Very Unhealthy             0.70  North
5     113.03                       Unhealthy             0.59  North
6      82.86  Unhealthy for sensitive groups             0.38   East
7     114.57                       Unhealthy             0.60  North
8      89.97  Unhealthy for sensitive groups             0.43  North
9     135.05                  Very Unhealthy             0.74   East
10     53.57                        Moderate             0.18   East
11     54.74                        Moderate             0.18  South
12     44.59                        Moderate             0.11  South
13     99.46                       Unhealthy             0.49  North
14     28.17                            Good             0.00  South
15     41.51                        Moderate             0.09   East
16     90.80                       Unhealthy             0.43   West
17     34.60                        Moderate             0.04   East
18     64.74  Unhealthy for sensitive groups             0.25  South
19     52.38                        Moderate             0.17  North
20    114.29                       Unhealthy             0.60   East

In [ ]:
features_df.to_csv(r"C:\Users\Shiva\Projects\climate-risk-intelligence\data\india_features.csv", index=False)

In [ ]:
features_df["risk_score"] = np.round(features_df["pm25_normalized"] * 100,1)
print(features_df["risk_score"])

0     100.0
1      62.0
2      66.0
3      78.0
4      70.0
5      59.0
6      38.0
7      60.0
8      43.0
9      74.0
10     18.0
11     18.0
12     11.0
13     49.0
14      0.0
15      9.0
16     43.0
17      4.0
18     25.0
19     17.0
20     60.0
Name: risk_score, dtype: float64

In [ ]:
features_df.to_csv(r"C:\Users\Shiva\Projects\climate-risk-intelligence\data\india_features.csv", index=False)

In [ ]:
encoded_df = pd.get_dummies(features_df["region"],dtype=int)
features_df = pd.concat([features_df,encoded_df],axis=1)
print(features_df)

     id                                           name   latitude  longitude  \
0    13   Delhi Technological University, Delhi - CPCB  28.744000  77.120000
1    17                        R K Puram, Delhi - DPCC  28.563262  77.186937
2    50                     Punjabi Bagh, Delhi - DPCC  28.674045  77.131023
3   103                Income Tax Office, Delhi - CPCB  28.623500  77.249400
4   235                  Anand Vihar, New Delhi - DPCC  28.646835  77.316032
5   236                      Mandir Marg, Delhi - DPCC  28.634100  77.200500
6   286                    Collectorate - Gaya - BSPCB  24.748969  84.943839
7   301                  Vikas Sadan, Gurugram - HSPCB  28.450124  77.026305
8   346                  MD University, Rohtak - HSPCB  28.876028  76.619464
9   354                               Lalbagh, DN Park  26.845786  80.938744
10  378                              Alandur Bus Depot  12.997114  80.191517
11  407                    Zoo Park, Hyderabad - TSPCB  17.349694  78.451437
12  412                      Peenya, Bengaluru - KSPCB  13.033900  77.513211
13  431                            IHBAS, Delhi - CPCB  28.682100  77.305000
14  594                  BTM Layout, Bengaluru - KSPCB  12.912811  77.609219
15  697                         Haldia, Haldia - WBPCB  22.060470  88.109737
16  703                   Collectorate Jodhpur - RSPCB  26.292064  73.037911
17  716  Rabindra Bharati University, Kolkata - WBSPCB  22.627875  88.380400
18  854                                     Chandrapur  19.950000  79.300000
19  860                    Sanjay Palace, Agra - UPPCB  27.198658  78.005981
20  985             Collectorate - Muzaffarpur - BSPCB  26.076200  85.411500

    pm25_avg                   risk_category  pm25_normalized region  \
0     172.83                  Very Unhealthy             1.00  North
1     117.44                       Unhealthy             0.62  North
2     123.52                  Very Unhealthy             0.66  North
3     141.59                  Very Unhealthy             0.78  North
4     129.00                  Very Unhealthy             0.70  North
5     113.03                       Unhealthy             0.59  North
6      82.86  Unhealthy for sensitive groups             0.38   East
7     114.57                       Unhealthy             0.60  North
8      89.97  Unhealthy for sensitive groups             0.43  North
9     135.05                  Very Unhealthy             0.74   East
10     53.57                        Moderate             0.18   East
11     54.74                        Moderate             0.18  South
12     44.59                        Moderate             0.11  South
13     99.46                       Unhealthy             0.49  North
14     28.17                            Good             0.00  South
15     41.51                        Moderate             0.09   East
16     90.80                       Unhealthy             0.43   West
17     34.60                        Moderate             0.04   East
18     64.74  Unhealthy for sensitive groups             0.25  South
19     52.38                        Moderate             0.17  North
20    114.29                       Unhealthy             0.60   East

    risk_score  East  North  South  West
0        100.0     0      1      0     0
1         62.0     0      1      0     0
2         66.0     0      1      0     0
3         78.0     0      1      0     0
4         70.0     0      1      0     0
5         59.0     0      1      0     0
6         38.0     1      0      0     0
7         60.0     0      1      0     0
8         43.0     0      1      0     0
9         74.0     1      0      0     0
10        18.0     1      0      0     0
11        18.0     0      0      1     0
12        11.0     0      0      1     0
13        49.0     0      1      0     0
14         0.0     0      0      1     0
15         9.0     1      0      0     0
16        43.0     0      0      0     1
17         4.0     1      0      0     0
18        25.0     0      0      1     0
19        17.0     0      1      0     0
20        60.0     1      0      0     0

In [ ]:
x = features_df[["latitude","longitude","East","West","North","South"]]
y = features_df[["risk_score"]]
print(x)
print(y)

     latitude  longitude  East  West  North  South
0   28.744000  77.120000     0     0      1      0
1   28.563262  77.186937     0     0      1      0
2   28.674045  77.131023     0     0      1      0
3   28.623500  77.249400     0     0      1      0
4   28.646835  77.316032     0     0      1      0
5   28.634100  77.200500     0     0      1      0
6   24.748969  84.943839     1     0      0      0
7   28.450124  77.026305     0     0      1      0
8   28.876028  76.619464     0     0      1      0
9   26.845786  80.938744     1     0      0      0
10  12.997114  80.191517     1     0      0      0
11  17.349694  78.451437     0     0      0      1
12  13.033900  77.513211     0     0      0      1
13  28.682100  77.305000     0     0      1      0
14  12.912811  77.609219     0     0      0      1
15  22.060470  88.109737     1     0      0      0
16  26.292064  73.037911     0     1      0      0
17  22.627875  88.380400     1     0      0      0
18  19.950000  79.300000     0     0      0      1
19  27.198658  78.005981     0     0      1      0
20  26.076200  85.411500     1     0      0      0
    risk_score
0        100.0
1         62.0
2         66.0
3         78.0
4         70.0
5         59.0
6         38.0
7         60.0
8         43.0
9         74.0
10        18.0
11        18.0
12        11.0
13        49.0
14         0.0
15         9.0
16        43.0
17         4.0
18        25.0
19        17.0
20        60.0

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=42
)

In [ ]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(16, 6) (5, 6) (16, 1) (5, 1)

In [ ]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=100,random_state=42)
model.fit(x_train,y_train.values.ravel())
print(model)

RandomForestRegressor(random_state=42)

In [ ]:
y_pred = model.predict(x_test)
print(y_pred)
print(y_test)

[57.46 41.65 38.44 65.92 57.01]
    risk_score
0        100.0
17         4.0
15         9.0
1         62.0
8         43.0

In [ ]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test,y_pred)
print(mae)

25.512

In [ ]:
import time

collection_list_pm25 = []
collection_list_pm10 = []

for location_id, name in zip(clean_df["id"], clean_df["name"]):
    try:
        response = requests.get(
            f"https://api.openaq.org/v3/locations/{location_id}/sensors",
            headers=headers,
            timeout=30
        )
        if response.status_code == 200:
            for sensor in response.json()["results"]:
                if sensor["parameter"]["name"] == "pm25":
                    if sensor["summary"] is not None:
                        avg_pm25 = sensor["summary"]["avg"]
                        collection_list_pm25.append((location_id, name, avg_pm25))
                elif sensor["parameter"]["name"] == "pm10":
                    if sensor["summary"] is not None:
                        avg_pm10 = sensor["summary"]["avg"]
                        collection_list_pm10.append((location_id, name, avg_pm10))
    except Exception as e:
        print(f"Failed for {name}: {e}")
    time.sleep(0.5)

df1 = pd.DataFrame(collection_list_pm25, columns=["location_id", "name", "pm25_avg"])
df2 = pd.DataFrame(collection_list_pm10, columns=["location_id", "name", "pm10_avg"])

    location_id                                           name     pm25_avg  \
0            13   Delhi Technological University, Delhi - CPCB   172.831336
1            17                        R K Puram, Delhi - DPCC   135.690776
2            17                        R K Puram, Delhi - DPCC   135.690776
3            17                        R K Puram, Delhi - DPCC    99.181818
4            17                        R K Puram, Delhi - DPCC    99.181818
5            50                     Punjabi Bagh, Delhi - DPCC   128.774238
6            50                     Punjabi Bagh, Delhi - DPCC   128.774238
7            50                     Punjabi Bagh, Delhi - DPCC   118.272727
8            50                     Punjabi Bagh, Delhi - DPCC   118.272727
9           103                Income Tax Office, Delhi - CPCB   141.592259
10          235                  Anand Vihar, New Delhi - DPCC   157.999618
11          235                  Anand Vihar, New Delhi - DPCC   157.999618
12          235                  Anand Vihar, New Delhi - DPCC   100.000000
13          235                  Anand Vihar, New Delhi - DPCC   100.000000
14          236                      Mandir Marg, Delhi - DPCC   113.032575
15          286                    Collectorate - Gaya - BSPCB    82.862666
16          301                  Vikas Sadan, Gurugram - HSPCB   114.570686
17          301                  Vikas Sadan, Gurugram - HSPCB   114.570686
18          301                  Vikas Sadan, Gurugram - HSPCB  2112.883333
19          301                  Vikas Sadan, Gurugram - HSPCB  2112.883333
20          346                  MD University, Rohtak - HSPCB    89.971503
21          354                               Lalbagh, DN Park   135.052329
22          378                              Alandur Bus Depot    53.568709
23          407                    Zoo Park, Hyderabad - TSPCB    48.485878
24          407                    Zoo Park, Hyderabad - TSPCB    48.485878
25          407                    Zoo Park, Hyderabad - TSPCB    61.000000
26          407                    Zoo Park, Hyderabad - TSPCB    61.000000
27          412                      Peenya, Bengaluru - KSPCB    44.591306
28          431                            IHBAS, Delhi - CPCB    99.456788
29          594                  BTM Layout, Bengaluru - KSPCB    28.171332
30          697                         Haldia, Haldia - WBPCB    41.508556
31          703                   Collectorate Jodhpur - RSPCB    90.795043
32          716  Rabindra Bharati University, Kolkata - WBSPCB    34.600000
33          854                                     Chandrapur    64.744416
34          860                    Sanjay Palace, Agra - UPPCB    92.157854
35          860                    Sanjay Palace, Agra - UPPCB    92.157854
36          860                    Sanjay Palace, Agra - UPPCB    12.600000
37          860                    Sanjay Palace, Agra - UPPCB    12.600000
38          910                     Victoria Memorial - WBSPCB     0.000000
39          985             Collectorate - Muzaffarpur - BSPCB   114.291053

      pm10_avg
0          NaN
1   255.044040
2   179.625000
3   255.044040
4   179.625000
5   247.956141
6   189.454545
7   247.956141
8   189.454545
9   221.329166
10  371.278580
11  266.000000
12  371.278580
13  266.000000
14  209.489553
15         NaN
16  113.322222
17    0.000000
18  113.322222
19    0.000000
20   77.444703
21         NaN
22         NaN
23   98.661634
24  120.400000
25   98.661634
26  120.400000
27         NaN
28         NaN
29         NaN
30   81.884293
31  200.207342
32  143.992940
33  135.764516
34  175.114217
35   81.600000
36  175.114217
37   81.600000
38   86.227389
39         NaN

In [ ]:
pm25_avg_over_900 = df1[(df1["pm25_avg"] < 900) & (df1["pm25_avg"] > 0)]
pm25_avg_filtered = np.round(pm25_avg_over_900.groupby(["location_id"])["pm25_avg"].mean().reset_index(),2)

In [ ]:
pm10_avg_over_900 = df2[(df2["pm10_avg"] < 900) & (df2["pm10_avg"] > 0)]
pm10_avg_filtered = np.round(pm10_avg_over_900.groupby(["location_id"])["pm10_avg"].mean().reset_index(),2)

In [ ]:
df = pd.merge(pm25_avg_filtered,pm10_avg_filtered , on=["location_id"], how="left")
df = df.dropna()
print(df)

    location_id  pm25_avg  pm10_avg
1            17    117.44    217.33
2            50    123.52    218.71
3           103    141.59    221.33
4           235    129.00    318.64
5           236    113.03    209.49
7           301    114.57    113.32
8           346     89.97     77.44
11          407     54.74    109.53
15          697     41.51     81.88
16          703     90.80    200.21
17          716     34.60    143.99
18          854     64.74    135.76
19          860     52.38    128.36

In [ ]:
final_df = pd.merge(clean_df,df,on="location_id",how="left")
print(final_df)

     id                                           name   latitude  longitude  \
0    12                           SPARTAN - IIT Kanpur  26.519000  80.233000
1    13   Delhi Technological University, Delhi - CPCB  28.744000  77.120000
2    15                                    IGI Airport  28.560000  77.094000
3    16                                    Civil Lines  28.678700  77.226200
4    17                        R K Puram, Delhi - DPCC  28.563262  77.186937
5    50                     Punjabi Bagh, Delhi - DPCC  28.674045  77.131023
6   103                Income Tax Office, Delhi - CPCB  28.623500  77.249400
7   235                  Anand Vihar, New Delhi - DPCC  28.646835  77.316032
8   236                      Mandir Marg, Delhi - DPCC  28.634100  77.200500
9   286                    Collectorate - Gaya - BSPCB  24.748969  84.943839
10  301                  Vikas Sadan, Gurugram - HSPCB  28.450124  77.026305
11  346                  MD University, Rohtak - HSPCB  28.876028  76.619464
12  354                               Lalbagh, DN Park  26.845786  80.938744
13  378                              Alandur Bus Depot  12.997114  80.191517
14  407                    Zoo Park, Hyderabad - TSPCB  17.349694  78.451437
15  412                      Peenya, Bengaluru - KSPCB  13.033900  77.513211
16  431                            IHBAS, Delhi - CPCB  28.682100  77.305000
17  594                  BTM Layout, Bengaluru - KSPCB  12.912811  77.609219
18  697                         Haldia, Haldia - WBPCB  22.060470  88.109737
19  703                   Collectorate Jodhpur - RSPCB  26.292064  73.037911
20  716  Rabindra Bharati University, Kolkata - WBSPCB  22.627875  88.380400
21  854                                     Chandrapur  19.950000  79.300000
22  860                    Sanjay Palace, Agra - UPPCB  27.198658  78.005981
23  910                     Victoria Memorial - WBSPCB  22.572646  88.363895
24  985             Collectorate - Muzaffarpur - BSPCB  26.076200  85.411500

    location_id  pm25_avg  pm10_avg
0            12       NaN       NaN
1            13       NaN       NaN
2            15       NaN       NaN
3            16       NaN       NaN
4            17    117.44    217.33
5            50    123.52    218.71
6           103    141.59    221.33
7           235    129.00    318.64
8           236    113.03    209.49
9           286       NaN       NaN
10          301    114.57    113.32
11          346     89.97     77.44
12          354       NaN       NaN
13          378       NaN       NaN
14          407     54.74    109.53
15          412       NaN       NaN
16          431       NaN       NaN
17          594       NaN       NaN
18          697     41.51     81.88
19          703     90.80    200.21
20          716     34.60    143.99
21          854     64.74    135.76
22          860     52.38    128.36
23          910       NaN       NaN
24          985       NaN       NaN

In [ ]:
final_df = final_df.drop(columns="location_id")
final_df = final_df.dropna()
print(final_df)

     id                                           name   latitude  longitude  \
4    17                        R K Puram, Delhi - DPCC  28.563262  77.186937
5    50                     Punjabi Bagh, Delhi - DPCC  28.674045  77.131023
6   103                Income Tax Office, Delhi - CPCB  28.623500  77.249400
7   235                  Anand Vihar, New Delhi - DPCC  28.646835  77.316032
8   236                      Mandir Marg, Delhi - DPCC  28.634100  77.200500
10  301                  Vikas Sadan, Gurugram - HSPCB  28.450124  77.026305
11  346                  MD University, Rohtak - HSPCB  28.876028  76.619464
14  407                    Zoo Park, Hyderabad - TSPCB  17.349694  78.451437
18  697                         Haldia, Haldia - WBPCB  22.060470  88.109737
19  703                   Collectorate Jodhpur - RSPCB  26.292064  73.037911
20  716  Rabindra Bharati University, Kolkata - WBSPCB  22.627875  88.380400
21  854                                     Chandrapur  19.950000  79.300000
22  860                    Sanjay Palace, Agra - UPPCB  27.198658  78.005981

    pm25_avg  pm10_avg
4     117.44    217.33
5     123.52    218.71
6     141.59    221.33
7     129.00    318.64
8     113.03    209.49
10    114.57    113.32
11     89.97     77.44
14     54.74    109.53
18     41.51     81.88
19     90.80    200.21
20     34.60    143.99
21     64.74    135.76
22     52.38    128.36

In [ ]:
custom_bins = [0,30,60,90,120,250,float('inf')]
group_names = ['Good','Moderate','Unhealthy for sensitive groups','Unhealthy','Very Unhealthy','Hazardous']
final_df["risk_category_pm25"] = pd.cut(final_df["pm25_avg"],bins=custom_bins,labels = group_names,right=False)
final_df["risk_category_pm10"] = pd.cut(final_df["pm10_avg"],bins=custom_bins,labels = group_names,right=False)

final_df[["name", "pm25_avg", "pm10_avg","risk_category_pm25","risk_category_pm10"]]

,name,pm25_avg,pm10_avg,risk_category_pm25,risk_category_pm10
4,"R K Puram, Delhi - DPCC",117.44,217.33,Unhealthy,Very Unhealthy
5,"Punjabi Bagh, Delhi - DPCC",123.52,218.71,Very Unhealthy,Very Unhealthy
6,"Income Tax Office, Delhi - CPCB",141.59,221.33,Very Unhealthy,Very Unhealthy
7,"Anand Vihar, New Delhi - DPCC",129.00,318.64,Very Unhealthy,Hazardous
8,"Mandir Marg, Delhi - DPCC",113.03,209.49,Unhealthy,Very Unhealthy
10,"Vikas Sadan, Gurugram - HSPCB",114.57,113.32,Unhealthy,Unhealthy
11,"MD University, Rohtak - HSPCB",89.97,77.44,Unhealthy for sensitive groups,Unhealthy for sensitive groups
14,"Zoo Park, Hyderabad - TSPCB",54.74,109.53,Moderate,Unhealthy
18,"Haldia, Haldia - WBPCB",41.51,81.88,Moderate,Unhealthy for sensitive groups
19,Collectorate Jodhpur - RSPCB,90.80,200.21,Unhealthy,Very Unhealthy
20,"Rabindra Bharati University, Kolkata - WBSPCB",34.60,143.99,Moderate,Very Unhealthy
21,Chandrapur,64.74,135.76,Unhealthy for sensitive groups,Very Unhealthy
22,"Sanjay Palace, Agra - UPPCB",52.38,128.36,Moderate,Very Unhealthy

In [ ]:
final_df["pm25_normalized"] = np.round((final_df["pm25_avg"] - final_df["pm25_avg"].min()) / (final_df["pm25_avg"].max() - final_df["pm25_avg"].min()),2)
final_df["pm10_normalized"] = np.round((final_df["pm10_avg"] - final_df["pm10_avg"].min()) / (final_df["pm10_avg"].max() - final_df["pm25_avg"].min()),2)
print(final_df)

     id                                           name   latitude  longitude  \
4    17                        R K Puram, Delhi - DPCC  28.563262  77.186937
5    50                     Punjabi Bagh, Delhi - DPCC  28.674045  77.131023
6   103                Income Tax Office, Delhi - CPCB  28.623500  77.249400
7   235                  Anand Vihar, New Delhi - DPCC  28.646835  77.316032
8   236                      Mandir Marg, Delhi - DPCC  28.634100  77.200500
10  301                  Vikas Sadan, Gurugram - HSPCB  28.450124  77.026305
11  346                  MD University, Rohtak - HSPCB  28.876028  76.619464
14  407                    Zoo Park, Hyderabad - TSPCB  17.349694  78.451437
18  697                         Haldia, Haldia - WBPCB  22.060470  88.109737
19  703                   Collectorate Jodhpur - RSPCB  26.292064  73.037911
20  716  Rabindra Bharati University, Kolkata - WBSPCB  22.627875  88.380400
21  854                                     Chandrapur  19.950000  79.300000
22  860                    Sanjay Palace, Agra - UPPCB  27.198658  78.005981

    pm25_avg  pm10_avg  pm25_normalized  pm10_normalized
4     117.44    217.33             0.77             0.49
5     123.52    218.71             0.83             0.50
6     141.59    221.33             1.00             0.51
7     129.00    318.64             0.88             0.85
8     113.03    209.49             0.73             0.46
10    114.57    113.32             0.75             0.13
11     89.97     77.44             0.52             0.00
14     54.74    109.53             0.19             0.11
18     41.51     81.88             0.06             0.02
19     90.80    200.21             0.53             0.43
20     34.60    143.99             0.00             0.23
21     64.74    135.76             0.28             0.21
22     52.38    128.36             0.17             0.18

In [ ]:
final_df["region"] = final_df.apply(lambda row: "East" if row['longitude'] > 80 else "West" if row['longitude'] < 76 else "North" if row['latitude'] > 26 and row['longitude'] > 76 and row['longitude'] < 80 else "South" if row['latitude'] < 22 and row['longitude'] > 76 and row['longitude'] < 80 else "Central",axis = 1)
print(final_df[["name","region","pm25_avg","pm10_avg"]])

                                             name region  pm25_avg  pm10_avg
4                         R K Puram, Delhi - DPCC  North    117.44    217.33
5                      Punjabi Bagh, Delhi - DPCC  North    123.52    218.71
6                 Income Tax Office, Delhi - CPCB  North    141.59    221.33
7                   Anand Vihar, New Delhi - DPCC  North    129.00    318.64
8                       Mandir Marg, Delhi - DPCC  North    113.03    209.49
10                  Vikas Sadan, Gurugram - HSPCB  North    114.57    113.32
11                  MD University, Rohtak - HSPCB  North     89.97     77.44
14                    Zoo Park, Hyderabad - TSPCB  South     54.74    109.53
18                         Haldia, Haldia - WBPCB   East     41.51     81.88
19                   Collectorate Jodhpur - RSPCB   West     90.80    200.21
20  Rabindra Bharati University, Kolkata - WBSPCB   East     34.60    143.99
21                                     Chandrapur  South     64.74    135.76
22                    Sanjay Palace, Agra - UPPCB  North     52.38    128.36

In [ ]:
final_df["risk_score_pm25"] = np.round(final_df["pm25_normalized"] * 100,1)
final_df["risk_score_pm10"] = np.round(final_df["pm10_normalized"] * 100,1)

In [ ]:
final_df["risk_score"] = ((final_df["risk_score_pm25"] + final_df["risk_score_pm10"])/2)
final_df = final_df.drop(columns="risk_score_pm25")
final_df = final_df.drop(columns="risk_score_pm10")

print(final_df)

     id                                           name   latitude  longitude  \
4    17                        R K Puram, Delhi - DPCC  28.563262  77.186937
5    50                     Punjabi Bagh, Delhi - DPCC  28.674045  77.131023
6   103                Income Tax Office, Delhi - CPCB  28.623500  77.249400
7   235                  Anand Vihar, New Delhi - DPCC  28.646835  77.316032
8   236                      Mandir Marg, Delhi - DPCC  28.634100  77.200500
10  301                  Vikas Sadan, Gurugram - HSPCB  28.450124  77.026305
11  346                  MD University, Rohtak - HSPCB  28.876028  76.619464
14  407                    Zoo Park, Hyderabad - TSPCB  17.349694  78.451437
18  697                         Haldia, Haldia - WBPCB  22.060470  88.109737
19  703                   Collectorate Jodhpur - RSPCB  26.292064  73.037911
20  716  Rabindra Bharati University, Kolkata - WBSPCB  22.627875  88.380400
21  854                                     Chandrapur  19.950000  79.300000
22  860                    Sanjay Palace, Agra - UPPCB  27.198658  78.005981

    pm25_avg  pm10_avg  pm25_normalized  pm10_normalized  \
4     117.44    217.33             0.77             0.49
5     123.52    218.71             0.83             0.50
6     141.59    221.33             1.00             0.51
7     129.00    318.64             0.88             0.85
8     113.03    209.49             0.73             0.46
10    114.57    113.32             0.75             0.13
11     89.97     77.44             0.52             0.00
14     54.74    109.53             0.19             0.11
18     41.51     81.88             0.06             0.02
19     90.80    200.21             0.53             0.43
20     34.60    143.99             0.00             0.23
21     64.74    135.76             0.28             0.21
22     52.38    128.36             0.17             0.18

                risk_category_pm25              risk_category_pm10 region  \
4                        Unhealthy                  Very Unhealthy  North
5                   Very Unhealthy                  Very Unhealthy  North
6                   Very Unhealthy                  Very Unhealthy  North
7                   Very Unhealthy                       Hazardous  North
8                        Unhealthy                  Very Unhealthy  North
10                       Unhealthy                       Unhealthy  North
11  Unhealthy for sensitive groups  Unhealthy for sensitive groups  North
14                        Moderate                       Unhealthy  South
18                        Moderate  Unhealthy for sensitive groups   East
19                       Unhealthy                  Very Unhealthy   West
20                        Moderate                  Very Unhealthy   East
21  Unhealthy for sensitive groups                  Very Unhealthy  South
22                        Moderate                  Very Unhealthy  North

    risk_score
4         63.0
5         66.5
6         75.5
7         86.5
8         59.5
10        44.0
11        26.0
14        15.0
18         4.0
19        48.0
20        11.5
21        24.5
22        17.5

In [ ]:
final_df.to_csv(r"C:\Users\Shiva\Projects\climate-risk-intelligence\data\india_features_v2.csv", index=False)

In [ ]:
encoded_df = pd.get_dummies(final_df["region"],dtype=int)
final_df = pd.concat([final_df,encoded_df],axis=1)
print(final_df)

     id                                           name   latitude  longitude  \
4    17                        R K Puram, Delhi - DPCC  28.563262  77.186937
5    50                     Punjabi Bagh, Delhi - DPCC  28.674045  77.131023
6   103                Income Tax Office, Delhi - CPCB  28.623500  77.249400
7   235                  Anand Vihar, New Delhi - DPCC  28.646835  77.316032
8   236                      Mandir Marg, Delhi - DPCC  28.634100  77.200500
10  301                  Vikas Sadan, Gurugram - HSPCB  28.450124  77.026305
11  346                  MD University, Rohtak - HSPCB  28.876028  76.619464
14  407                    Zoo Park, Hyderabad - TSPCB  17.349694  78.451437
18  697                         Haldia, Haldia - WBPCB  22.060470  88.109737
19  703                   Collectorate Jodhpur - RSPCB  26.292064  73.037911
20  716  Rabindra Bharati University, Kolkata - WBSPCB  22.627875  88.380400
21  854                                     Chandrapur  19.950000  79.300000
22  860                    Sanjay Palace, Agra - UPPCB  27.198658  78.005981

    pm25_avg  pm10_avg  pm25_normalized  pm10_normalized  \
4     117.44    217.33             0.77             0.49
5     123.52    218.71             0.83             0.50
6     141.59    221.33             1.00             0.51
7     129.00    318.64             0.88             0.85
8     113.03    209.49             0.73             0.46
10    114.57    113.32             0.75             0.13
11     89.97     77.44             0.52             0.00
14     54.74    109.53             0.19             0.11
18     41.51     81.88             0.06             0.02
19     90.80    200.21             0.53             0.43
20     34.60    143.99             0.00             0.23
21     64.74    135.76             0.28             0.21
22     52.38    128.36             0.17             0.18

                risk_category_pm25              risk_category_pm10 region  \
4                        Unhealthy                  Very Unhealthy  North
5                   Very Unhealthy                  Very Unhealthy  North
6                   Very Unhealthy                  Very Unhealthy  North
7                   Very Unhealthy                       Hazardous  North
8                        Unhealthy                  Very Unhealthy  North
10                       Unhealthy                       Unhealthy  North
11  Unhealthy for sensitive groups  Unhealthy for sensitive groups  North
14                        Moderate                       Unhealthy  South
18                        Moderate  Unhealthy for sensitive groups   East
19                       Unhealthy                  Very Unhealthy   West
20                        Moderate                  Very Unhealthy   East
21  Unhealthy for sensitive groups                  Very Unhealthy  South
22                        Moderate                  Very Unhealthy  North

    risk_score  East  North  South  West
4         63.0     0      1      0     0
5         66.5     0      1      0     0
6         75.5     0      1      0     0
7         86.5     0      1      0     0
8         59.5     0      1      0     0
10        44.0     0      1      0     0
11        26.0     0      1      0     0
14        15.0     0      0      1     0
18         4.0     1      0      0     0
19        48.0     0      0      0     1
20        11.5     1      0      0     0
21        24.5     0      0      1     0
22        17.5     0      1      0     0

In [ ]:
x = final_df[["latitude","longitude","pm25_normalized","pm10_normalized","East","West","North","South"]]
y = final_df[["risk_score"]]
print(x)
print(y)

     latitude  longitude  pm25_normalized  pm10_normalized  East  West  North  \
4   28.563262  77.186937             0.77             0.49     0     0      1
5   28.674045  77.131023             0.83             0.50     0     0      1
6   28.623500  77.249400             1.00             0.51     0     0      1
7   28.646835  77.316032             0.88             0.85     0     0      1
8   28.634100  77.200500             0.73             0.46     0     0      1
10  28.450124  77.026305             0.75             0.13     0     0      1
11  28.876028  76.619464             0.52             0.00     0     0      1
14  17.349694  78.451437             0.19             0.11     0     0      0
18  22.060470  88.109737             0.06             0.02     1     0      0
19  26.292064  73.037911             0.53             0.43     0     1      0
20  22.627875  88.380400             0.00             0.23     1     0      0
21  19.950000  79.300000             0.28             0.21     0     0      0
22  27.198658  78.005981             0.17             0.18     0     0      1

    South
4       0
5       0
6       0
7       0
8       0
10      0
11      0
14      1
18      0
19      0
20      0
21      1
22      0
    risk_score
4         63.0
5         66.5
6         75.5
7         86.5
8         59.5
10        44.0
11        26.0
14        15.0
18         4.0
19        48.0
20        11.5
21        24.5
22        17.5

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=42
)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(10, 8) (3, 8) (10, 1) (3, 1)

In [ ]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=100,random_state=42)
model.fit(x_train,y_train.values.ravel())
print(model)

RandomForestRegressor(random_state=42)

In [ ]:
y_pred = model.predict(x_test)
print(y_pred)
print(y_test)

[17.065 41.87  63.445]
    risk_score
21        24.5
19        48.0
4         63.0

In [ ]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test,y_pred)
print(mae)

4.670000000000001